sudo: required
services:
  - docker

before_install:
  - docker build amuljadhav222/react-test -f Dockerfile.Dev ./client

script:
  - docker run amuljadhav222/react-test npm test -- --coverage

after_success:
  - docker build -t amuljadhav222/multi-docker-client ./client
  - docker build -t amuljadhav222/multi-docker-nginx ./nginx
  - docker build -t amuljadhav222/multi-docker-server ./server
  - docker build -t amuljadhav222/multi-docker-worker ./worker

  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them to docker hu
  - docker push amuljadhav222/multi-docker-client
  - docker push amuljadhav222/multi-docker-nginx
  - docker push amuljadhav222/multi-docker-server
  - docker push amuljadhav222/multi-docker-worker